2017-06-16 04:42:19,458 ERROR 2414 [egg-mongoose] mongodb://127.0.0.1/yiweiv3 disconnected
2017-06-16 04:42:19,460 ERROR 947 [egg-mongoose] mongodb://127.0.0.1/yiweiv3 disconnected
2017-06-16 04:42:49,579 ERROR 947 nodejs.DisconnectedError: [egg-mongoose]Ran out of retries trying to reconnect to "127.0.0.1:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.
    at MongooseError.DisconnectedError (/Users/wujunyi/Desktop/node/eggRest/node_modules/.4.10.0@mongoose/lib/error/disconnected.js:21:11)
    at Server.<anonymous> (/Users/wujunyi/Desktop/node/eggRest/node_modules/.4.10.0@mongoose/lib/drivers/node-mongodb-native/connection.js:64:31)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/wujunyi/Desktop/node/eggRest/node_modules/.2.1.10@mongodb-core/lib/topologies/server.js:319:16)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/wujunyi/Desktop/node/eggRest/node_modules/.2.1.10@mongodb-core/lib/connection/pool.js:309:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/wujunyi/Desktop/node/eggRest/node_modules/.2.1.10@mongodb-core/lib/connection/connection.js:177:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
message: '[egg-mongoose]Ran out of retries trying to reconnect to "127.0.0.1:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.'
name: 'DisconnectedError'
pid: 947
hostname: bogon

2017-06-16 04:42:49,554 ERROR 2414 nodejs.DisconnectedError: [egg-mongoose]Ran out of retries trying to reconnect to "127.0.0.1:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.
    at MongooseError.DisconnectedError (/Users/wujunyi/Desktop/node/eggRest/node_modules/.4.10.0@mongoose/lib/error/disconnected.js:21:11)
    at Server.<anonymous> (/Users/wujunyi/Desktop/node/eggRest/node_modules/.4.10.0@mongoose/lib/drivers/node-mongodb-native/connection.js:64:31)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/wujunyi/Desktop/node/eggRest/node_modules/.2.1.10@mongodb-core/lib/topologies/server.js:319:16)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/wujunyi/Desktop/node/eggRest/node_modules/.2.1.10@mongodb-core/lib/connection/pool.js:309:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/wujunyi/Desktop/node/eggRest/node_modules/.2.1.10@mongodb-core/lib/connection/connection.js:177:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
message: '[egg-mongoose]Ran out of retries trying to reconnect to "127.0.0.1:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.'
name: 'DisconnectedError'
pid: 2414
hostname: bogon

2017-06-16 22:10:06,860 ERROR 1630 nodejs.ClusterClientNoResponseError: client no response in 3998647ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wujunyi/Desktop/node/eggRest/node_modules/.1.6.4@cluster-client/lib/leader.js:72:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
name: 'ClusterClientNoResponseError'
pid: 1630
hostname: localhost

2017-06-16 23:51:28,686 ERROR 1630 nodejs.ClusterClientNoResponseError: client no response in 548760ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wujunyi/Desktop/node/eggRest/node_modules/.1.6.4@cluster-client/lib/leader.js:72:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
name: 'ClusterClientNoResponseError'
pid: 1630
hostname: localhost

2017-06-17 03:36:36,125 ERROR 1630 nodejs.ClusterClientNoResponseError: client no response in 7204481ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wujunyi/Desktop/node/eggRest/node_modules/.1.6.4@cluster-client/lib/leader.js:72:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
name: 'ClusterClientNoResponseError'
pid: 1630
hostname: localhost

2017-06-17 04:37:20,299 ERROR 1630 nodejs.ClusterClientNoResponseError: client no response in 3604129ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wujunyi/Desktop/node/eggRest/node_modules/.1.6.4@cluster-client/lib/leader.js:72:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
name: 'ClusterClientNoResponseError'
pid: 1630
hostname: localhost

2017-06-17 05:38:04,465 ERROR 1630 nodejs.ClusterClientNoResponseError: client no response in 3604142ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wujunyi/Desktop/node/eggRest/node_modules/.1.6.4@cluster-client/lib/leader.js:72:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
name: 'ClusterClientNoResponseError'
pid: 1630
hostname: localhost

2017-06-17 07:38:48,786 ERROR 1630 nodejs.ClusterClientNoResponseError: client no response in 7204288ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wujunyi/Desktop/node/eggRest/node_modules/.1.6.4@cluster-client/lib/leader.js:72:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
name: 'ClusterClientNoResponseError'
pid: 1630
hostname: localhost

2017-06-17 09:38:48,970 ERROR 1630 nodejs.ClusterClientNoResponseError: client no response in 7160159ms exceeding maxIdleTime 30000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/wujunyi/Desktop/node/eggRest/node_modules/.1.6.4@cluster-client/lib/leader.js:72:23)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
name: 'ClusterClientNoResponseError'
pid: 1630
hostname: localhost

